version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 30s

  fastapi-app:
    build:
      context: .
      dockerfile: ./Dockerfile  # Path to your Dockerfile for FastAPI
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  mynetwork:
