name: Run Tests with Docker Compose

# Trigger on push or pull request to the main branch
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu version

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Compose using hoverkraft-tech/compose-action
      - name: Run Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"

      # Step 3: Run tests in the running container
      - name: Run tests with pytest
        run: |
          docker-compose exec fastapi-app pytest -s /app/tests

      # Step 4: Tear down Docker Compose services after tests
      - name: Tear down Docker Compose services
        run: |
          docker-compose down
