name: Run Tests with Docker Compose

# Trigger on push or pull request to the main branch
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu version

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 3: Set up Docker Compose using hoverkraft-tech/compose-action
      - name: Run Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"

      # Step 4: Run tests in the running container
      - name: Run tests with pytest
        run: |
          docker-compose exec fastapi-app pytest -s /app/tests

      # Step 5: Tear down Docker Compose services after tests
      - name: Tear down Docker Compose services
        run: |
          docker-compose down
